### ISSUE TITLE
Feature Request: Superhero Name

### ISSUE THREAD

**Issue by jwynn6** [Lavve/MMM-MagicSuperHero#2]
Can we get the superhero's name displayed? There's an awful lot of them I don't recognize by sight. Might be fun to be able to toggle on their fullName, aliases and alteregos.

**Comment by Lavve** [comment]
Hi! Thanks for your comment and suggestions. The name should definitely be there, I must have forgotten to implement that part of the module. An update will be merged to the repo soon.

Regarding the fullName, aliases and alter egos, not all of the characters have those nodes. Some of them have tons of aliases, some nothing at all. I've not added this to the module since I'm sure how to implement the names in a nice way, and without make the module cluttery. Suggestions for this are more than welcome. :)

**Comment by jwynn6** [comment]
Looks fantastic! Alias and alters may look ok in a tiny text cloud under everything. But I think you are correct that it would look cluttered, leaving it as it is now is perfect.

**Comment by Lavve** [comment]
Great, thanks for your feedback!
